# -*- coding: utf-8 -*-
# RAW: hojas por unidad -> (fecha, actividad, material literal)
RAW = {}

RAW["CASTORES"] = [
("J-16/07 mañana","Montaje de tiendas","Tienda de campaña x2; Listones; Tablas de madera; Cuerda pita- 2 rollos; Tijeras de punta redonda; Martillo de goma; Lona + segunda estructura de tienda (mochilero); Listones de los viejos para estructuras y mástil; Bandera de castores; Poleas para banderas; Imperdibles x4"),
("J-16/07 tarde 1","Organizar mochilero","Cajas grandes de cartón del chino por niño +3"),
("J-16/07 tarde 2","Normas de campamento + juegos","Papel continuo 1m x 1m; Rotuladores; Celo gordo; Tela pequeña o pañoleta (pañuelito); Balón"),
("V-17/07 mañana","Construcciones zona común","Listones; Tablas de madera; Cuerda pita- 2 rollos; Tijeras de punta redonda; Martillo de goma; Listones de los viejos para estructuras y mástil; Bandera de castores; Poleas para banderas; Imperdibles x4"),
("V-17/07 tarde","Taller insignias","Goma eva de colores; Imperdibles; Pompones pequeños; Tijeras; Pegamentos; Silicona líquida para pegar los imperdibles"),
("V-17/07 tarde 2","T.E.G.A. (Torneo de Globos)","Papel plastificado (lo lleva la comisión); Celo; 150 globos; 4 tobilleras de gimnasio o similares (ref Temu en el doc)"),
("V-17/07 noche","Rastreo nocturno","Cintas reflectantes amarillas; Cintas reflectantes naranjas; Paquete de sobres; Leyendas de las constelaciones (comisión) - imprimir antes"),
("S-18/07 tarde 1","Gran Juego: El Taj perdido (con Lobatos)","Témperas (colores a concretar); Taj Mahal impreso (se encarga la unidad); Pinceles; Papel seda de colores; Folios; Balde; Agua; Goma eva de colores (vale con recortes); Pajitas; Arco; Papel continuo 1x1"),
("S-18/07 tarde 2","Hacer mochilas acampada volante","Mochilas de cada castor; Ropa; Papel continuo; Rotuladores"),
("S-18/07 noche","Taller constelaciones","Aislantes; 3 mantas; Puntero láser; Altavoz (música relajante); Texto reflexión 'El Tren de los Sueños de Plata' (imprimir); Imagen de constelaciones (imprimir); Frontal o linterna del móvil"),
("D-19 a M-21/07","Acampada volante (x3 días)","Lumi gas; Comida del día (menú de volantes); Botiquín; Chalecos y Walkie talkies; Gorras y cantimploras; Cazuela y cuchara de madera; Mechero; Crema solar; Bolsas de basura; Fairy; Estropajo; Títulos fotocopia; Tarjetas sanitarias niños"),
("D-19/07 tarde","Taller relajación/yoga","Esterillas"),
("M-21/07 tarde 1","Entrenamiento Caza Gamusino","Bolsas de basura; Pinturas de cara; Rotuladores; Palitos luminosos x3; Casquería (texturas, en descripción)"),
("M-21/07 tarde 2","Taller de tortitas (con Exploradores)","Camping gas x4; Sartén x4; Bol grande x4; Varillas de mano (o tenedores) x4; Cazo para servir x4; Espátula x4; Toppings: Nocilla x3, chocolate x3, mermelada x4 botes; Medidas por niño: Harina 80-100g, Leche 100-120ml, 1/2 huevo, 1 cda azúcar, dado de mantequilla, pizca levadura en polvo, pizca de sal"),
("M-21/07 tarde 2b","Taller pulseras (lo dan Exploradores)","Cordino (1.5 m por participante)"),
("M-21/07 noche","Caza Gamusino","6 sacos de tela; Frontales; Ropa oscura"),
("X-22/07 tarde 1","Diseño de camisetas","Camiseta blanca o básica (cada castor debe llevar una); Pintura para telas; Gomas de plástico; Bolsas de plástico (en descripción, para reposar las camisetas)"),
("X-22/07 tarde 2","Actividad Clan Ícaro","Cartulina; Rotuladores; Papel y boli"),
("X-22/07 noche","Juegos de mesa","Juegos de mesa de las bases"),
("J-23/07 mañana","Taller de cocina - Nariyal Ladoo","2-3 morteros (los que haya); 2 hornillos; 2 cazuelas medianas; Fruta en almíbar sobrante; Compra (20 niños): Coco rallado 1kg; Leche condensada 2 botes grandes (740g); Granadina 1 botella; Mantequilla 1 bote; Cardamomo 2 botes de semillas (o 1 en polvo)"),
("J-23/07 tarde 1","Progresión Personal (mandalas)","Plantillas de mandalas circulares (comisión, imprimir antes); Lápices de colores o ceras"),
("V-24/07 mañana","Actividad de agua: El descenso del Ganges","4 garrafas de agua (da igual tamaño); 4 botellas pequeñas; Gomas elásticas (paquete); Palillos largos (bases); Cartulina blanca A4; Témperas y 10 pinceles; Tijeras; Cola blanca 2 botes; 4 cubos; 2 barreños; 2 sillas; Canicas; 20 esponjas de las que pesan con agua"),
("V-24/07 noche","Consejo de troncos","Lumi y bombona; Bandera; Tótem 'Paco'; Tronquitos (se encarga la unidad); Cuadernos; Chapa naranja (vueltas de pañoleta); Insignia de arat; Insignia del tronco (promesa); Gorro castor; Awen (peluche castor)"),
("S-25/07 tarde 1","Taller de arcilla","X kilos de arcilla (AÑADIR CUANDO SE SEPA Nº DE NIÑOS); Bolsas de basura para tapar mesas; Botes de témperas; Pinceles; Caja de palillos; Cuerda pita (por si alguno hace collar); Imágenes de amuletos impresas (en descripción)"),
("S-25/07 tarde 2","Hacer mochilas para día de padres","Mochilas niños; Cajas de ropa; Bolsas de basura para ropa y cosas perdidas"),
("S-25/07 noche","Juegos nocturnos (stalking)","Silbato; Pañoletas; Linternas"),
("D-26/07 (lluvia)","Lluvia: Flipbook","Folios; Rotuladores; Grapadora"),
("Lluvia","Lluvia: Pintar piedras","Rotuladores algo gorditos y normales"),
("Lluvia","Lluvia: Carteles con letras chinas","Telas blancas (2 por niño, tamaño bufanda); Pintura de manos negra; Imágenes impresas de letras chinas"),
("Bolsa de juegos","Cuento de imágenes","Folios; Tijeras; Grapadora; Bolis"),
("Bolsa de juegos","Taller de sobres y cartas","Cartulinas de colores A4 (1 por niño); Folios; Bolis (1 por niño); Sellos (1 por niño); Gomets o pegatinas de las bases"),
("Bolsa de juegos","Dinámica abanico","Folios; Rotuladores; Bolis"),
("Bolsa de juegos","Taller pintar piedras","Pinceles y témperas"),
("Bolsa de juegos","Talleres pinza","Pinzas; Goma eva; Cartulina; Pegamento de goma eva; Lápices y gomas"),
("19-21/07","MENÚ VOLANTE (para 14: 12 castores + 2 GC)","Manzanas 14; Filetes de lomo 70; Tranchetes 32; Paté 5 latas; Noodles 10 paquetes; Salchichas 8 paquetes; Leche deshidratada para 8L; Cola Cao a ojo; Galletas 14 rulos; Pasta carbonara 9 paquetes; Nocilla 2 botes; Sopa 5 sobres; Salchichón 1 rulo; Tang 3 sobres de cada sabor; Frutos secos variados; Leche condensada antigoteo 2 botes; Bolsas zip 1 paquete; Sal en papel albal; Fairy; Estropajo; Pan 4 barras; A mayores: bolsas de basura, papel albal, chalecos, papel higiénico, 1 cazuela grande o 2 pequeñas, cuchara de madera, 1 quemador y 1 bombona pequeña desechables, mechero, botiquín, walkie talkies, plato/poto/cubiertos GC"),
]

RAW["LOBATOS"] = [
("J-16/07 mañana","Montaje","Tiendas; Hierros; Tablas; Listones; Piquetas; Mazas"),
("J-16/07 tarde 1","Construcción de parcela","Listones; Elementos de la naturaleza; Mazas; Cuerda pita; Clavos"),
("J-16/07 tarde 2","Juegos","Conos chinos; Balón goma espuma; Pañoletas"),
("V-17/07 mañana","Juegos India","Pinturas cara pintacaras (de pincel, no de pinturilla); Fieltro marrón oscuro x4 láminas A3 (bandas de flecos indias); Telas de las bases; Piedras (de la campa); Una cazuela; Pelota de tenis; Parchís y fichas x3; Incienso"),
("V-17/07 tarde 1","Territorios","Cartulinas A4; Dos fotos (a mayores, no de los niños); Cuerda pita (1m); Papel albal; Precinto"),
("V-17/07 tarde 2","De aventura en la India","Pañoleta; Aros; Bancos; Comba; Conos chinos; Pelota blanda"),
("V-17/07 noche","Juegos nocturnos","Frontales; Silbatos; Objetos varios que se cojan de material"),
("S-18/07 tarde 1","El Taj perdido (con Castores)","Témperas; Taj Mahal impreso (se encarga la unidad); Pinceles; Papel seda de colores; Folios; Balde; Agua; Goma eva de colores (recortes); Pajitas; Arco; Papel continuo 1x1"),
("S-18/07 tarde 2","Preparación mochila","Papel continuo; Rotulador; Bolsas de basura grande 1 x niño; Bolsa de basura mediana 1 x niño"),
("D-19 a M-21/07","Ruta volante (x3 días)","Mapas 312-I, 315-II, 315-IV, 316-III; Lumi gas; Comida del día (menú de volantes); Botiquín; Chalecos y Walkie talkies; Gorras y cantimploras; Cazuela y cuchara de madera; Mechero; Crema solar; Bolsas de basura; Papel higiénico; Fairy; Estropajo; Títulos fotocopia; Tarjetas sanitarias niños"),
("D-19/07 tarde","Taller de pulseras","Hilo coreano de diferentes colores (3 m x niño); Celo; Tijeras"),
("L-20/07 tarde","ILLRA","Silbato monitores; Folios; Bolígrafos; Gorra/Bolsa; Puño de mono (ganador); Cartulina para el himno; Agua (cada uno su cantimplora)"),
("M-21/07 tarde 1","Bailes tradicionales indios + país","Telas; Mandalas (20); Rotuladores, pinturas, ceras; Altavoz; Música india"),
("M-21/07 tarde 2","Taller de relajación","Crema hidratante; Altavoz; Esterillas de los niños"),
("M-21/07 noche","Teleclub","Juegos de mesa; Folios; Bolígrafos"),
("X-22/07 tarde","El amuleto del elefante sagrado (orientación)","5 brújulas; Balón blando; Folios; 5 bolígrafos; Abalorios grandes y pequeños de distintos colores (7 bolsas, si son pequeñas más); Cuerda de pulsera de encoger y estirar negra"),
("X-22/07 noche","Taller de estrellas","20 cartulinas negras; 15 pinturas blancas; Cuerda pita; Pinzas de madera; Esterillas; Altavoz"),
("J-23/07 mañana","Voluntariado conjunto Lobatos-Pioneros","(Lo trae el niño) Botella de agua; Gorra; Mochila; Comida; Ropa cómoda; Camiseta de cambio; Calzado montaña; Protector solar; Botiquín; Guantes; Bolsas de basura"),
("J-23/07 día","Piscina pueblo (con Pioneros)","(Lo trae el niño) 2 bañadores; Toalla; Chanclas; Gorro de baño; Gafas de natación; Peine; Bolsa ropa mojada; Protector solar; Gorra; Gafas de sol; Botella de agua; Cartas para jugar; Comida al pueblo (bocadillo)"),
("J-23/07 tarde 2","Actividad lobatos (Clan Ícaro - Charlie y David)","Set de petanca; Discos para lanzar; Cuerda (gorda mejor) y una rueda/algo que pese; Un banco; Botellas/conos/cosas que se caigan; Un palo/algo para meter aros; Aros"),
("V-24/07 mañana","Gymkana de agua","Lona grande o plástico resistente; Jabón líquido o detergente suave; Cubos de agua 6; Globos de agua 100; Churros; Conos; Vasos de plástico 6; Cucharas de plástico; Pelotas de pin pon 10; Tapones 6"),
("V-24/07 tarde 1","Clan Ícaro: brújula casera y potabilizar","Brújulas; Papel; Bolis; Pañoleta con tochos; Camping gas; Mechero; Harina; Sal; Agua; Lona; Cuerda; Piquetas; Botella de plástico; Arena fina; Arena gruesa; Carbón vegetal"),
("V-24/07 tarde 2","Sport & Scouts (con Exploradores)","2 balones de fútbol; 6 conos; 2 toallas; Cuerda pita y lona"),
("V-24/07 noche","Roca del Consejo","Bandera de lobatos; 2 lumis; Akela; Sangre de toro"),
("S-25/07 mañana","Promesas + progresión personal","Cuaderno de caza; Bolsas de seisenas; Bolígrafos; Insignias territorios"),
("S-25/07 tarde 1","Taller de tortilla de patata","4 sartenes grandes; 4 boles grandes; 6 cuchillos; 4 peladores de patatas; 4 tablas de cortar; 1 plato grande o tapa; 4 platos grandes; 4 tenedores; Papel de cocina; Ingredientes (para 5 niños): 6 huevos, 4 patatas medianas, media cebolla, aceite de oliva y sal (calcular con nº de lobatos)"),
("S-25/07 tarde 2","Lobatolimpiadas","Palo de escoba; Conos chinos; Pelota volley; Pintura acrílica; Cola de ratón x2; Lámina goma eva dorada brillantina A4"),
("S-25/07 noche","Lobatolimpiadas mentales","Piezas de metal de las bases que encajan; Papel; Bolis"),
("D-26/07 noche","Velada de humor","Saco con cosas para teatrillos (del campamento); Folios; Bolígrafos"),
("L-27/07 mañana","Poza","Pelota de voleibol; Esponjas x10"),
("L-27/07 tarde 1","Atrapasueños","Platos de cartón blancos; Tijeras; Rotuladores; Cinta de regalo (mucha); Folios de colores; Abalorios; Estrellas, pegatinas, bolitas de lana, etc."),
("L-27/07 tarde-noche","Picoteo al estilo lobato","Platos; Bebidas (2 coca-cola, agua, 1 fanta naranja, 1 aquarius); Pan de molde; Jamón york; Queso; Bolsas grandes de gominolas con y sin azúcar; Gusanitos, patatas...; Nutella; Fruta del campamento; Juegos de mesa"),
("M-28/07 mañana","Hotel de insectos","Malla de alambre 1m x 30cm aprox (ref Temu en el doc); Cajas de madera tipo fruta x8 (~30cm); Navajas (de los niños); Cola para madera 2 botes; Hojas, piñas, piedras (de allí); Cartones (3-4 cajas grandes); Cuerda pita (2 rollos); 10 ganchos de tornillo"),
("M-28/07 tarde 1","Taller sexualidad: línea del tiempo","Folios; Bolígrafos; Tijeras; Pegamento; Papel continuo"),
("M-28/07 tarde-noche","Olimpiadas tarde + vivacs","Lonas impermeables; Picas; Cuerda; Martillos o maza; Cuerda pita; Conos; Folios; Bolis; Saco y cuerda gorda; 5 aros pequeños para prender; Pañuelos de colores (x8); Alambre; Gasolina; Mechero"),
("X-29/07 tarde","Tipi indio - Miss y Mister","Folios de colores; Rotuladores; Cola; Tijeras; Palillos de madera largos; Una caja de cartón; Un ovillo de lana"),
("X-29/07 tarde 2","Evaluación","Folios; Bolis; Papel crepé verde, rojo y amarillo"),
]
