# -*- coding: utf-8 -*-
RAW2 = {}

RAW2["EXPLORADORES"] = [
("J-16/07 mañana+tarde","Construcciones rústicas","2 rollos de pita grandes; 6 alcotanas; Maderas varias para parcela y FELSA; Clavos (indeterminados); 2 poleas para bandera; Tiendas; Piquetas; Listón para mástil; Listón para potero; Listones para portada; Estructura para mochilero con hierros y lonas; Estructura para tendedero"),
("J-16/07 tarde","Juegos (Tropiolimpiadas - cerbatanas)","Tubos de PVC liso 16mm cortados a 50cm (1 por explorador); Lanzadoras tipo Nerf (unidad, solo monitores); Dardos de gomaespuma (unidad); Lija de grano fino; Cinta aislante de colores; 30 pinzas de 3 colores distintos (10 de cada)"),
("V-17/07 mañana","Presentación profunda","Tarjetas de personajes (unidad); Cofre cerrado con candado y varias llaves; Folios y rotuladores; 5 sobres; Post-its (3 como mucho)"),
("V-17/07 tarde 1","Construcciones adicionales","Sombrajo; Clavos; Cuerda gruesa (ni soga ni pita); Tablones de madera; Tablita para columpio; Tablas rotas; Listones circulares"),
("V-17/07 tarde 2","Inauguración de la FELSA","(Se encarga la unidad) Cuadrilátero acabado; Corchera; Nombres de los niños; Rana de sorteo; Chinchetas; Caja con pañoletas de juego, cinturones, silbato, pañoleta de ganador; Cancioneros"),
("V-17/07 noche","Velada de código morse","Silbato o linterna x3; Folios (unos 4); 2 rotuladores; 5 objetos 'tesoro': 2 mazas, 2 telas/objetos amarillos, 2 pinceles, 2 botellines o latas"),
("S-18/07 tarde 1","Taller de hornillo","Lata de aluminio 2 por niño; Alcohol 96º; Alambre; Mechero"),
("S-18/07 tarde 2","Preparación de volantes","Bolsas de basura (para guardar ropa); Botiquín con lo indispensable (kraalete); Comida volante"),
("S-18/07 noche","Preparación de volantes (noche)","Mapas; Frontales; Lumi; Brújula"),
("D-19 a M-21/07","Volante (x3 días)","Mapas; Comida; Menaje; Botiquín unidad; Chalecos; Navaja; Mochilas volante; Brújulas; Walkie-talkies"),
("D-19/07 tarde","Taller de relajación","Esterilla"),
("L-20/07 tarde","Actividad maristas","Cuerda pita (unos metros); Caja de madera que se pueda cerrar; Folios x5"),
("M-21/07 tarde","Taller pulseras con Castores","Cordino (1.5 m por participante)"),
("M-21/07 noche","Teleclub","Caja de juegos: Gobbit, baraja de cartas, Jungle Speed, Virus..."),
("X-22/07 tarde 1","Actividad Clan Ícaro (Trivial)","Tablero de trivial (impreso); Dados; Fichas; Frisbee; Poto; Balón; Pelotas de pin pon"),
("X-22/07 tarde 2","Jugger","Escudos; Lanzas; Dobles; Espadas; Pelota jugger; Cinta americana; Silbato"),
("X-22/07 noche","Velada de terror","5 pieles de kiwi; 1 bote de espárragos; 1 paquete de chía; 1 caja; 1 llave; 10 lonas; 10 mantas; Espaguetis; 3 campanas; 5 vendas o pañuelos; Máscaras (las del año pasado)"),
("J-23/07 mañana","Servicio en el pueblo","Pendiente del voluntariado, se suelen necesitar: Guantes; Chalecos reflectantes"),
("J-23/07 tarde 1","Pruebas Herberth","Puzzles de las bases"),
("J-23/07 noche","Velada con Pioneros: Estratego","Silbatos monitores; Papel y boli; Anexo tabla (fotocopiar)"),
("V-24/07 mañana","Masterchef pizza","Ingredientes: Harina de fuerza; Levadura de panadero; Agua; Sal; Aceite de oliva; Tomate frito; Jamón york; Bacon ahumado; Pepperoni o salami; Salchichas Frankfurt; Atún en conserva; Anchoas; Champiñones laminados; Pimientos rojo y verde; Cebolla; Aceitunas negras sin hueso; Maíz dulce; Piña en su jugo; Rúcula; Mozzarella; Huevos; Miel; Orégano; Pimienta negra; Ajo en polvo"),
("V-24/07 tarde 1","FELSA","(Se encarga la unidad) Cuadrilátero; Corchera; Nombres; Rana de sorteo; Chinchetas; Caja con pañoletas, cinturones, silbato, pañoleta ganador; Cancioneros"),
("V-24/07 tarde 2","Sport & Scouts (con Lobatos)","2 balones de fútbol; 6 conos; 2 toallas; Cuerda pita y lona"),
("V-24/07 noche","Carrera de orientación nocturna","Cintas reflectantes; Cinta roja, verde y azul (2m de cada); Folios"),
("S-25/07 tarde 1","Scape room","Folios; Candados (todos los que haya, distintos tipos); Tarros con líquidos de color (x5 colores); Relojes x4 (si hay más mejor); Boli con tinta invisible (hay comprados); Cubitera x2; Cuerda; Báscula; Lentejas x300; Libro con muchas páginas"),
("S-25/07 tarde 1b","Complementaria scape room","Folios"),
("S-25/07 tarde 2","Alimentación y buenos hábitos","20 folios; 3 bolis"),
("S-25/07 noche","Velada de debate","Papel con los 'supervivientes' (fotocopiar)"),
("D-26/07 noche","Preparación de raids","(Pedir a menú) Huevos cocidos 1/explorador +5; Patatas cocidas 1/explorador +6; Mapas de la zona x6; Brújula x6; Rafia x6; Cuerda pita x50 metros"),
("L-27/07","Raids","Mismo material que la noche previa; Chalecos reflectantes 1 por explorador y kraalete; Reflexiones impresas (unidad)"),
("M-29/07 mañana","Desmontar construcciones","Rastrillo; Alcotana; Herramientas"),
("M-29/07 tarde 1","Miss y Mister: sacos de especias","Cuadrado de tela 10x10cm por niño; 40cm de cordino por niño; 5 cartulinas; Rotuladores"),
("M-29/07 tarde 2","Evaluación (cuentas)","Cuentas amarillas, verdes y rojas (~30 por niño, más verdes); 60cm de cordino por niño (oscuro mejor)"),
("Lluvia","Guardián de las llaves / Pueblo duerme","Manojo de llaves o cascabel; Pañoleta para vendar ojos; Periódico enrollado o churro de piscina; Pinzas (cobras)"),
]

RAW2["PIONEROS"] = [
("J-16 y V-17/07","Construcciones","10m sombrajo; 100m cuerda pita; 5 listones (puerta + sombrajo); Alcotanas"),
("V-17/07 tarde","Gymkhana deportes","Bancos, mesa (circuito); Conos bajos de colores; Cuerda gorda (sogatira); Palas de playa y pelota; Palas de ping pong y pelotitas; Red de volleyball; Petanca; Medallas de goma eva (las hace el kraalete)"),
("V-17/07 noche","Taller de estrellas","Cartulinas amarillas 2 A4; Precinto; Bolígrafos/Rotus; Tijeras; Cuento/leyendas de estrellas; Aislantes (los suyos)"),
("S-18/07 tarde 1","Actividad Clan Ícaro - Drogas","Papel; Boli; Botellas de plástico; Algodón; Cigarrillos; Mechero; Balde; Cartas"),
("S-18/07 tarde 2","Preparación volantes","Comida volantes y menaje; Botiquín pequeño; Rafias"),
("S-18/07 noche","Preparación volantes (noche)","Mapas (poner números); Frontales; Lumis"),
("D-19 a M-21/07","Volantes (x3 días)","Mapa hoja 316 21-13 Quintanar de la Sierra; Comida + menaje; Botiquín unidad; Chalecos; Navaja; Mochilas volante; Reflexiones"),
("D-19/07 noche","Juegos de cartas tradicionales","Baraja española de cartas COMPLETA"),
("M-21/07 tarde","Piscina pueblo Quintanar","(Lo trae el niño) Toalla; Bañador y chanclas; Mochila pequeña"),
("L-20/07 noche","Pulseras","Gomitas de colores para pulseras; Cordino y cuerda para pulseras y trenzas de pelo"),
("M-21/07 tarde 2","Relax","Altavoz (kraalete) y móvil; Cremita aftersun; Aislantes (los nuestros)"),
("M-21/07 noche","Velada pioneros","Black stories impresas; Juegos de mesa de la caja: 'El Mortal' y 'Family Business'"),
("X-22/07 tarde","Carrera de orientación","Trozos de telas pequeños (o cinta reflectante) de 2 colores; Sobres pequeños x10; Brújulas; Pruebas (kraalete); Fotocopias mapa campa x4; Rotus; Folios; Bolígrafos; Cámara de fotos"),
("X-22/07 noche","Velada teleclub","Juegos de la caja; Baraja de cartas"),
("J-23/07 mañana","Voluntariado con Lobatos","Guantes; Bolsas basura; Lo que nos pidan"),
("J-23/07 tarde 1","Juegos de agua","Bañadores, chanclas y toalla (niños); Balones blanditos para agua; Globos de agua (hinchados en barreño); Jarras de cocina; Preguntas scouts (kraalete); Cubo grande de colores (barreño)"),
("J-23/07 tarde 2","Taller pintar tote bags","Tote bags 100% algodón x1 por chaval; Pinturas acrílicas (o pintura para tela) de colores; Pinceles de varios tamaños; Vasos de plástico (mezclar/limpiar); Un cartón por bolso"),
("J-23/07 noche","Velada conjunta Tropa - Stratego","Frontales; Silbato"),
("V-24/07 mañana","Taller de cocina (tarta de galletas)","Hornillo o camping gas; Sartenes y ollas; Tablas de cortar; Cucharas, espátulas, boles; Papel de aluminio; MENÚ: Galletas tipo María/Digestive/avena; Queso crema untable familiar; Azúcar blanco o glass; Mermelada fresa/frambuesa/melocotón; Fruta de temporada; Mantequilla o leche condensada"),
("V-24/07 tarde 2","Fe","Folios de colores; Bolis; V y F fotocopiado (Vali); Pinturas de palo; Rotus de colores"),
("V-24/07 noche","Velada autopercepción","Post-its de colores; Bolis; Rotus; Un trozo de papel continuo"),
("S-25/07 mañana","Miss y Mister","Miss y Mister ya plastificados; Perforadora"),
("S-25/07 tarde 1","Sexualidad","Una mandarina por participante; Rotuladores; Papel continuo; Cinta adhesiva; Post-its; Bolígrafos"),
("S-25/07 tarde 2","Refugiados por un día","2 folios de 2 colores diferentes (NO blancos); Bolis; Noticias fotocopiadas (Vali); Roles y situaciones fotocopiados (Vali)"),
("S-25/07 noche","Velada NNEE","Papelitos de términos fotocopiados (Vali); Petanca; Sillas de camping del kraal (prestadas)"),
("D-26/07 noche","Preparación raids","Papeles raid sorteo; (Avisar a menú: patatas y huevos cocidos)"),
("L-27 a M-28/07","Raids","Patatas cocidas; Huevos cocidos; Mochilas raids; Navaja/frontal; Bolsas basura; Papel higiénico; Folios reflexiones"),
("X-29/07 tarde","Evaluación + Miss y Mister + velada","Miss y Mister plastificados; Rotuladores permanentes finos; Hilo de colores para atar (gordito, no lana ni de pulseras fino); Mandalas fotocopiados en cartulina blanca; Rotuladores de colores; Pinturas de palo"),
("X-29/07 noche","Velada final conjunta","Frontales; Lumis para el centro; Miss y Mister grupales"),
("Lluvia","Taller puzzle móvil","Plantilla puzzle (fotocopiar); Pinturillas y rotuladores de colores; Pegamento; Tijeras"),
("Lluvia","Taller de tejer","Lana de colores; Cartones (recortes pequeños); Palillos alargados tipo brocheta"),
("Lluvia","Decorar fotos","Foto impresa en papel de foto (cada uno la suya); Hilo de colores (fino, no lana); Punzón; Agujas"),
("Lluvia","Cuenco serpentina","Cola blanca; Serpentina de colores; Tijeras"),
("Lluvia","Pulseras","Hilo de pulsera, 7-8 colores; Tijeras; Mechero; Celo; Imperdibles"),
("Lluvia","Pintar mandalas","Mandalas (fotocopiar); Pinturas de palo; Rotuladores de colores"),
]

RAW2["RUTAS PANDORA"] = [
("J-16/07","Actividad de adicciones con pipis","Papel; Boli; Botella de plástico; Algodón; Cigarrillos; Mechero; Balde; Cartas"),
("V-17/07","PPV","Cuerda; Post-its; Bolígrafos; Folios; Permanentes; Rotuladores"),
("S-18/07","Preparación acampada volante","Mapas de la zona (pdte)"),
("D-19 a M-21/07","Acampada volante (x3 días)","Camping gas; Comida del día; Cazuelas y cucharas de madera; Chalecos; Mapas de la zona 316I, 316III, 348I y 348III; Botiquín; Cerillas o mechero; Limpieza (bolsas basura, fairy, estropajo); Títulos fotocopiados; Tarjetas sanitarias"),
("Volante noche","Línea de la vida","Velas pequeñas (15); Cerillas/mecheros; Aislantes; Reflexiones"),
("X-22/07","Estiramientos post-volante","Esterillas"),
("X-22/07 noche","Juegos de mesa","Juegos de mesa nuestros y de las bases"),
("J-23/07","Cocina con hándicaps (gyozas/empanadillas)","Cinta aislante; Pañoleta (vendar ojos); Cascos inalámbricos y un móvil (o tapones); Camping gas; Bandejas; Papel film; Comida: masa de empanadillas; 750g harina de trigo; Sal; 1L caldo de pollo; 2 pechugas de pollo; 4 huevos; 4 dientes de ajo; Salsa de soja; Jengibre; 1 cebolleta; 2 puerros; Salmón; Carne picada de cerdo 250g; Pimienta; Aceite; Agua"),
("J-23/07 noche","Debates con roles","Papel; Boli"),
("V-24/07","Voluntariado Neila","Falta confirmar si dejan todo o llevamos nosotros; Coche/furgo para llegar"),
("V-24/07 noche","PPV (velada)","Velas altas; Mantas; Altavoz; Mini tronquitos; Permanentes finos negros; Cajas pandora (ellas)"),
("S-25/07","Cambio climático y ecosistemas autosostenibles","Frascos grandes de cristal con tapa hermética; Rotulador; Carbón vegetal; Pala o pica para excavar; Papel de cocina; Naturaleza recolectada en campa y río"),
("S-25/07 tarde","Jugger con el Ícaro","Armas del jugger"),
("S-25/07 noche","Velada de reflexión con el Ícaro","Papel; Boli"),
("D-26/07","Rapel","Furgoneta; Material dejado por la empresa"),
("D-26/07 noche","Stalking con el Clan Ícaro","Frontales; Papeles; Bolis"),
("L-27/07","Preparación raids","Mapas de la zona (pdte)"),
("L-27 a M-28/07","Raids","8 huevos cocidos; 4 patatas cocidas; Chalecos; Botiquín"),
("X-29/07 tarde","Miss y Mister (llaveros)","Pasta moldeable de secado al aire: carne, rosa, azul, rojo, amarillo, blanco, negro; Goma eva rosa pandora con purpurina; Rotuladores negros; Tijeras; Cola de ratón que pase por pernos de argolla; Pernos de argolla pequeñitos; Anillas de llavero"),
("Reserva","Reflexión personal","Altavoz; Folios; Bolígrafos"),
("Reserva","Carrera de orientación","Mapa de la zona; Brújulas; Pinzas de orientación"),
]

RAW2["RUTAS ICARO"] = [
("J-16/07","Construcciones","Tienda; Cuerda pita; Mástil; Bandera rutas; Imperdibles; Cordino para bandera; Portada: 6 listones; Cartel rutas; Hierros y listones para tendedero; Listones sobrantes"),
("V-17/07","Taller Eva","Folios; Bolis"),
("V-17/07","Taller David","Folios; Bolígrafo; Bingo (David)"),
("V-17/07","PPV (Vali)","Cuadernos PPV (los suyos); Bolis; Tarjetas mochila a color impresa (A5); Rotus de colores; Papelitos dinámica"),
("V-17/07 noche","Velada Vision Board","Cartulina A3 grises claras; Periódicos y revistas (un par de cada); Rotuladores de colores y permanentes; Bolis"),
("S-18/07","Taller para Pioneros - Drogas","Papel; Boli; Botellas de plástico; Algodón; Cigarrillos; Mechero; Balde; Cartas"),
("S-18/07","Actividad moverse (Charlie)","Pelotas; Cuerda; Papel; Un boli"),
("S-18/07 noche","Preparación volantes","Mapas de la zona 316I, 316III, 348I y 348III; Comida y menaje; Botiquín unidad; Chalecos"),
("D-19 a M-21/07","Volantes (x3 días)","Mapas de la zona 316I, 316III, 348I y 348III; Comida y menaje; Botiquín unidad; Chalecos; Mochilas volante; Cordino"),
("Volante noche","Línea de la vida","Velas pequeñas (15); Mechero/cerillas; Aislantes; Reflexiones y preguntas fotocopiadas (Vali)"),
("M-21/07","Talleres personales (Charlie)","Rotus; Navaja; Una fruta para cada uno (naranja)"),
("M-21/07 noche","Juegos de mesa","Caja de juegos de mesa"),
("X-22/07","Actividad para Tropa: Trivial","Tablero de trivial (impreso); Dados; Fichas; Frisbee; Poto; Balón; Pelotas de pin pon"),
("X-22/07","Actividad para Castores","Cartulina; Rotuladores; Papel y boli"),
("X-22/07 noche","Taller feminismo (actividad país)","Folios; Bolis; Lista de preguntas impresa (Eva y Vali); Perfil de debate impreso (Eva y Vali)"),
("J-23/07","Voluntariado Manuela","Guantes; Chalecos; Bolsas de basura; Tijeras; Alguna herramienta básica"),
("J-23/07","Actividad para Lobatos (Charlie y David)","Set de petanca; Discos para lanzar; Cuerda gorda y una rueda/algo que pese; Un banco; Botellas/conos; Un palo para meter aros; Aros"),
("V-24/07","¿Por qué la rutina nos provoca estrés?","Papel; Boli"),
("V-24/07","Taller Manu","Folios; Bolis"),
("V-24/07","El cáncer de la dopamina","Papel y bolis"),
("V-24/07","Técnicas scouts (brújula casera, potabilizar)","Brújulas; Papel; Bolis; Pañoleta con tochos; Camping gas; Mechero; Harina; Sal; Agua; Lona; Cuerda; Piquetas; Botella de plástico; Arena fina; Arena gruesa; Carbón vegetal"),
("S-25/07","Jugger con Pandora","Armas de jugger; Balón de rugby"),
("S-26/07","Revisar olimpiadas + hacer premios","Goma eva de muchos colores (bastante); Ovillo de lana; Plumas; Rotulador punta fina; Abalorios"),
("D-26/07 noche","Stalking con Pandora y pipis","(Sin material listado)"),
("L-27/07","Preparación de raids","Lumis; Mapas"),
("L-27 a M-28/07","Raids","Comida raids; Chalecos reflectantes; Reflexiones (Vali); Patatas cocidas; Huevos cocidos; Papel higiénico; Bolsas de basura"),
("X-29/07 mañana","OLIMPIADAS (grupal)","Hierros de tiendas de 3-4 tamaños; Bancos del comedor; Balón; Mantas; Cuerda pita; Martillo; Clavos; Potos/vasos; Pelotas de pin-pon; Dos pañoletas; Vaso de plástico; Velas; Mechero; Sacos para carrera de sacos"),
]
